// ---- Tier 1: browser automation, run last. ----
  {
    id: "amazon_in",
    name: "Amazon.in",
    baseUrl: "https://www.amazon.in",
    kind: "BROWSER",
    currency: "INR",
    tier: 1,
    enabled: true,
    platformHint: "SWITCH",
    // A real browse-node category listing, not a keyword search — covers
    // both Switch and Switch 2 in one URL (confirmed ~47 pages), more
    // precise and more complete than the old "k=nintendo+switch+games"
    // free-text search.
    searchUrls: [
      "https://www.amazon.in/s?i=videogames&rh=n%3A976460031%2Cn%3A13995115031%2Cn%3A13995151031&dc&ds=v1%3AiZuYA9QV0eVzZbIDkLndPnQhVZrwc%2BriiE0a8ssyvMY&qid=1787339967&rnid=13995115031&ref=sr_nr_n_1&page={p}",
    ],
    note: "Real bot detection. Cards keyed on data-component-type, which is stabler than Amazon's class names.",
  },
  {
    id: "flipkart",
    name: "Flipkart",
    baseUrl: "https://www.flipkart.com",
    kind: "BROWSER",
    currency: "INR",
    tier: 1,
    enabled: true,
    platformHint: "SWITCH",
    // A real category page with platform facets applied (Switch + Switch 2
    // both, in one URL, confirmed ~7 pages) instead of a free-text search.
    searchUrls: [
      "https://www.flipkart.com/gaming/games/physical-game/pr?sid=4rr%2Cfa6%2C32v&marketplace=FLIPKART&p%5B%5D=facets.platform%255B%255D%3DSwitch&p%5B%5D=facets.platform%255B%255D%3DSwitch%2B2&page={p}",
    ],
    note: "Obfuscated, rotating class names. Adapter prefers __INITIAL_STATE__ over CSS for this reason.",
  },
  {
    id: "gamestheshop",
    name: "Games The Shop",
    baseUrl: "https://www.gamestheshop.com",
    kind: "BROWSER",
    currency: "INR",
    tier: 1,
    enabled: true,
    platformHint: "SWITCH",
    searchUrls: [
      "https://www.gamestheshop.com/search?condition=Physical&platforms=Nintendo+Switch&categories=Game+Software&page={p}",
      "https://www.gamestheshop.com/search?condition=Physical&platforms=Nintendo+Switch+2&categories=Game+Software&page={p}",
    ],
    note: "Custom Next.js storefront, not Shopify/WooCommerce — has no public product API, so it's scraped like Amazon/Flipkart. The &page={p} suffix is a guess; confirm/adjust once inspect.ts shows page 2's real URL shape.",
  },
  {
    id: "gamenation",
    name: "GameNation",
    baseUrl: "https://gamenation.in",
    kind: "BROWSER",
    currency: "INR",
    tier: 1,
    enabled: true,
    platformHint: "SWITCH",
    searchUrls: ["https://gamenation.in/PlayStation/?platform=nintendoSwitch%2CnintendoSwitch2&page={p}"],
    note: "Custom storefront (the /PlayStation/ path is misleading — it's their general catalogue, filtered by the platform query param to both Switch and Switch 2). &page={p} is a guess to confirm via inspect.ts.",
  },
  {
    id: "mcubegames",
    name: "Mcube Games",
    baseUrl: "https://www.mcubegames.in",
    kind: "BROWSER",
    currency: "INR",
    tier: 1,
    enabled: true,
    platformHint: "SWITCH",
    searchUrls: ["https://www.mcubegames.in/shop?platforms=60&platforms=93&page={p}"],
    note: "Custom storefront filtered by numeric platform IDs (60/93 = Switch/Switch 2 per the URL given). &page={p} is a guess to confirm via inspect.ts.",
  },
  {
    id: "e2zstore",
    name: "e2zSTORE",
    baseUrl: "https://e2zstore.com",
    kind: "BROWSER",
    currency: "INR",
    tier: 1,
    enabled: true,
    platformHint: "SWITCH",
    searchUrls: ["https://e2zstore.com/category/nintendo-games/?paged={p}"],
    note: "Every direct HTTP request (Store API and plain homepage fetch) failed here even though the site loads fine in a real browser — almost certainly bot protection blocking non-browser traffic, so it needs Playwright rather than the WooCommerce adapter. baseUrl switched from www to non-www to match the URL that's confirmed to load.",
  },
  {
    id: "playasia",
    name: "Play-Asia",
    baseUrl: "https://www.play-asia.com",
    kind: "BROWSER",
    currency: "INR",
    tier: 1,
    enabled: true,
    platformHint: "SWITCH",
    searchUrls: [
      "https://www.play-asia.com/en/search/nintendo+switch+games",
      "https://www.play-asia.com/en/search/nintendo+switch+2+games",
    ],
    note: "Pagination is click-based via DOM interaction rather than URL params. INR reference currency injected via session cookies.",
  },